INSERT INTO ITSM_CONFIGURATION_ITEMS (CIT_OID, CIT_ID, CIT_SEARCHCODE, CIT_NAME1, CIT_PRICE) VALUES (
  20001, 2001, 'CIT №1', 'Some item', 8.50
);

INSERT INTO ITSM_CONFIGURATION_ITEMS (CIT_OID, CIT_ID, CIT_SEARCHCODE, CIT_NAME1, CIT_PRICE, CIT_OWNER_PER_OID) VALUES (
  20002, 2002, 'CIT №2', 'Another item', 19.3, 1
);

INSERT INTO ITSM_CONFIGURATION_ITEMS (CIT_OID, CIT_ID, CIT_SEARCHCODE, CIT_OWNER_PER_OID) VALUES (
  20003, 2003, 'Nameless', 1
);

INSERT INTO ITSM_CONFIGURATION_ITEMS (CIT_OID, CIT_ID, CIT_SEARCHCODE, CIT_NAME1, CIT_PRICE, CIT_OWNER_PER_OID) VALUES (
  20004, 2004, 'searchcode', 'name', 99.9, 2
);