@startuml

' Схема смены статусов в Изменениях

[*] --> Зарегистрировано : Инициатор
Зарегистрировано -> Подготовка : Инициатор
Подготовка --> Реализация : Менеджер
Подготовка --> На_согласовании : Менеджер
Подготовка --> Решено : Менеджер
На_согласовании --> Подготовка : Менеджер
На_согласовании --> Согласование_завершено : Автоматически
Согласование_завершено --> Подготовка : Менеджер
Согласование_завершено --> Реализация : Менеджер
Реализация --> Решено : Исполнитель
Решено --> Подготовка : Менеджер
Решено --> [*]

@enduml